language: python
python:
  - "2.6"
  - "2.7"

install: 
  # - pip install -r _utilities/requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install codecov

script: 
  - coverage run _utilities/test.py

after_success:
  - coveralls
  - codecov